# Generated by Django 2.1.3 on 2018-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouseProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='stock_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
